[2025-05-18T09:55:58.765+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: uhi_index_analytics_pipeline_decompose.process_street manual__2025-05-17T05:12:03.413965+00:00 [queued]>
[2025-05-18T09:55:58.856+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: uhi_index_analytics_pipeline_decompose.process_street manual__2025-05-17T05:12:03.413965+00:00 [queued]>
[2025-05-18T09:55:58.862+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2025-05-18T09:55:58.868+0000] {taskinstance.py:1280} INFO - Starting attempt 2 of 2
[2025-05-18T09:55:58.869+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2025-05-18T09:55:59.209+0000] {taskinstance.py:1300} INFO - Executing <Task(PythonOperator): process_street> on 2025-05-17 05:12:03.413965+00:00
[2025-05-18T09:55:59.310+0000] {standard_task_runner.py:55} INFO - Started process 83 to run task
[2025-05-18T09:55:59.380+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'uhi_index_analytics_pipeline_decompose', 'process_street', 'manual__2025-05-17T05:12:03.413965+00:00', '--job-id', '228', '--raw', '--subdir', 'DAGS_FOLDER/uhi_pipeline_dag_decompose.py', '--cfg-path', '/tmp/tmpjdiveqj7']
[2025-05-18T09:55:59.391+0000] {standard_task_runner.py:83} INFO - Job 228: Subtask process_street
[2025-05-18T09:55:59.979+0000] {task_command.py:388} INFO - Running <TaskInstance: uhi_index_analytics_pipeline_decompose.process_street manual__2025-05-17T05:12:03.413965+00:00 [running]> on host ee2bb044a094
[2025-05-18T09:56:00.422+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=uhi_index_analytics_pipeline_decompose
AIRFLOW_CTX_TASK_ID=process_street
AIRFLOW_CTX_EXECUTION_DATE=2025-05-17T05:12:03.413965+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=manual__2025-05-17T05:12:03.413965+00:00
[2025-05-18T09:56:00.469+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/uhi_pipeline_dag_decompose.py", line 85, in process_street_data
    preprocess.input_data_handle(data["street"], type="street")
TypeError: 'NoneType' object is not subscriptable
[2025-05-18T09:56:00.543+0000] {taskinstance.py:1323} INFO - Marking task as FAILED. dag_id=uhi_index_analytics_pipeline_decompose, task_id=process_street, execution_date=20250517T051203, start_date=20250518T095558, end_date=20250518T095600
[2025-05-18T09:56:00.675+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 228 for task process_street ('NoneType' object is not subscriptable; 83)
[2025-05-18T09:56:00.743+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2025-05-18T09:56:00.972+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
