[2025-05-17T09:31:32.961+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: uhi_index_analytics_pipeline_decompose.process_population manual__2025-05-17T05:12:03.413965+00:00 [queued]>
[2025-05-17T09:31:33.339+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: uhi_index_analytics_pipeline_decompose.process_population manual__2025-05-17T05:12:03.413965+00:00 [queued]>
[2025-05-17T09:31:33.356+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2025-05-17T09:31:33.385+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 2
[2025-05-17T09:31:33.420+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2025-05-17T09:31:33.726+0000] {taskinstance.py:1300} INFO - Executing <Task(PythonOperator): process_population> on 2025-05-17 05:12:03.413965+00:00
[2025-05-17T09:31:33.964+0000] {standard_task_runner.py:55} INFO - Started process 1174 to run task
[2025-05-17T09:31:34.095+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'uhi_index_analytics_pipeline_decompose', 'process_population', 'manual__2025-05-17T05:12:03.413965+00:00', '--job-id', '213', '--raw', '--subdir', 'DAGS_FOLDER/uhi_pipeline_dag_decompose.py', '--cfg-path', '/tmp/tmp5av8njn6']
[2025-05-17T09:31:34.104+0000] {standard_task_runner.py:83} INFO - Job 213: Subtask process_population
[2025-05-17T09:31:35.227+0000] {task_command.py:388} INFO - Running <TaskInstance: uhi_index_analytics_pipeline_decompose.process_population manual__2025-05-17T05:12:03.413965+00:00 [running]> on host ee2bb044a094
[2025-05-17T09:31:35.110+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=uhi_index_analytics_pipeline_decompose
AIRFLOW_CTX_TASK_ID=process_population
AIRFLOW_CTX_EXECUTION_DATE=2025-05-17T05:12:03.413965+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2025-05-17T05:12:03.413965+00:00
[2025-05-17T09:31:35.220+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/uhi_pipeline_dag_decompose.py", line 117, in process_population_data
    preprocess.input_data_handle(data["population"], type="population")
TypeError: 'NoneType' object is not subscriptable
[2025-05-17T09:31:34.165+0000] {taskinstance.py:1323} INFO - Marking task as UP_FOR_RETRY. dag_id=uhi_index_analytics_pipeline_decompose, task_id=process_population, execution_date=20250517T051203, start_date=20250517T093133, end_date=20250517T093134
[2025-05-17T09:31:34.256+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 213 for task process_population ('NoneType' object is not subscriptable; 1174)
[2025-05-17T09:31:34.405+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2025-05-17T09:31:34.953+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
