[2025-05-18T09:55:58.474+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: uhi_index_analytics_pipeline_decompose.process_nyzd manual__2025-05-17T05:12:03.413965+00:00 [queued]>
[2025-05-18T09:55:58.591+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: uhi_index_analytics_pipeline_decompose.process_nyzd manual__2025-05-17T05:12:03.413965+00:00 [queued]>
[2025-05-18T09:55:58.611+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2025-05-18T09:55:58.614+0000] {taskinstance.py:1280} INFO - Starting attempt 2 of 2
[2025-05-18T09:55:58.622+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2025-05-18T09:55:58.814+0000] {taskinstance.py:1300} INFO - Executing <Task(PythonOperator): process_nyzd> on 2025-05-17 05:12:03.413965+00:00
[2025-05-18T09:55:58.989+0000] {standard_task_runner.py:55} INFO - Started process 81 to run task
[2025-05-18T09:55:59.004+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'uhi_index_analytics_pipeline_decompose', 'process_nyzd', 'manual__2025-05-17T05:12:03.413965+00:00', '--job-id', '226', '--raw', '--subdir', 'DAGS_FOLDER/uhi_pipeline_dag_decompose.py', '--cfg-path', '/tmp/tmpjqkaecra']
[2025-05-18T09:55:59.009+0000] {standard_task_runner.py:83} INFO - Job 226: Subtask process_nyzd
[2025-05-18T09:55:59.592+0000] {task_command.py:388} INFO - Running <TaskInstance: uhi_index_analytics_pipeline_decompose.process_nyzd manual__2025-05-17T05:12:03.413965+00:00 [running]> on host ee2bb044a094
[2025-05-18T09:56:00.140+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=uhi_index_analytics_pipeline_decompose
AIRFLOW_CTX_TASK_ID=process_nyzd
AIRFLOW_CTX_EXECUTION_DATE=2025-05-17T05:12:03.413965+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=manual__2025-05-17T05:12:03.413965+00:00
[2025-05-18T09:56:00.198+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/uhi_pipeline_dag_decompose.py", line 109, in process_nyzd_data
    preprocess.input_data_handle(data["nyzd"], type="nyzd")
TypeError: 'NoneType' object is not subscriptable
[2025-05-18T09:56:00.260+0000] {taskinstance.py:1323} INFO - Marking task as FAILED. dag_id=uhi_index_analytics_pipeline_decompose, task_id=process_nyzd, execution_date=20250517T051203, start_date=20250518T095558, end_date=20250518T095600
[2025-05-18T09:56:00.326+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 226 for task process_nyzd ('NoneType' object is not subscriptable; 81)
[2025-05-18T09:56:00.439+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2025-05-18T09:56:00.599+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
