[2025-05-18T09:55:58.867+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: uhi_index_analytics_pipeline_decompose.process_nysp manual__2025-05-17T05:12:03.413965+00:00 [queued]>
[2025-05-18T09:55:58.959+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: uhi_index_analytics_pipeline_decompose.process_nysp manual__2025-05-17T05:12:03.413965+00:00 [queued]>
[2025-05-18T09:55:58.962+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2025-05-18T09:55:58.964+0000] {taskinstance.py:1280} INFO - Starting attempt 2 of 2
[2025-05-18T09:55:58.966+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2025-05-18T09:55:59.083+0000] {taskinstance.py:1300} INFO - Executing <Task(PythonOperator): process_nysp> on 2025-05-17 05:12:03.413965+00:00
[2025-05-18T09:55:59.184+0000] {standard_task_runner.py:55} INFO - Started process 82 to run task
[2025-05-18T09:55:59.200+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'uhi_index_analytics_pipeline_decompose', 'process_nysp', 'manual__2025-05-17T05:12:03.413965+00:00', '--job-id', '227', '--raw', '--subdir', 'DAGS_FOLDER/uhi_pipeline_dag_decompose.py', '--cfg-path', '/tmp/tmpzftpn2t7']
[2025-05-18T09:55:59.201+0000] {standard_task_runner.py:83} INFO - Job 227: Subtask process_nysp
[2025-05-18T09:55:59.643+0000] {taskinstance.py:1077} INFO - Dependencies not met for <TaskInstance: uhi_index_analytics_pipeline_decompose.process_nysp manual__2025-05-17T05:12:03.413965+00:00 [running]>, dependency 'Task Instance Not Running' FAILED: Task is in the running state
[2025-05-18T09:55:59.734+0000] {taskinstance.py:1077} INFO - Dependencies not met for <TaskInstance: uhi_index_analytics_pipeline_decompose.process_nysp manual__2025-05-17T05:12:03.413965+00:00 [running]>, dependency 'Task Instance State' FAILED: Task is in the 'running' state.
[2025-05-18T09:55:59.751+0000] {local_task_job.py:147} INFO - Task is not able to be run
[2025-05-18T09:55:59.784+0000] {task_command.py:388} INFO - Running <TaskInstance: uhi_index_analytics_pipeline_decompose.process_nysp manual__2025-05-17T05:12:03.413965+00:00 [running]> on host ee2bb044a094
[2025-05-18T09:56:00.314+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=uhi_index_analytics_pipeline_decompose
AIRFLOW_CTX_TASK_ID=process_nysp
AIRFLOW_CTX_EXECUTION_DATE=2025-05-17T05:12:03.413965+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=manual__2025-05-17T05:12:03.413965+00:00
[2025-05-18T09:56:00.384+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/uhi_pipeline_dag_decompose.py", line 101, in process_nysp_data
    preprocess.input_data_handle(data["nysp"], type="nysp")
TypeError: 'NoneType' object is not subscriptable
[2025-05-18T09:56:00.478+0000] {taskinstance.py:1323} INFO - Marking task as FAILED. dag_id=uhi_index_analytics_pipeline_decompose, task_id=process_nysp, execution_date=20250517T051203, start_date=20250518T095558, end_date=20250518T095600
[2025-05-18T09:56:00.643+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 227 for task process_nysp ('NoneType' object is not subscriptable; 82)
[2025-05-18T09:56:00.713+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2025-05-18T09:56:00.841+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
